// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhJncEg7riTVLzdainBwXBEyUcJdhDvU',
    appId: '1:1073648909920:web:52c6b0132bcf39bc4c8d05',
    messagingSenderId: '1073648909920',
    projectId: 'aplikasi-olahraga-mahasi-e8a84',
    authDomain: 'aplikasi-olahraga-mahasi-e8a84.firebaseapp.com',
    storageBucket: 'aplikasi-olahraga-mahasi-e8a84.appspot.com',
    measurementId: 'G-TC5LSGRHNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_f0tcFvTWejmZUrGPcNUHrP0ks46ThU',
    appId: '1:1073648909920:android:d3fb48b4e13ba7174c8d05',
    messagingSenderId: '1073648909920',
    projectId: 'aplikasi-olahraga-mahasi-e8a84',
    storageBucket: 'aplikasi-olahraga-mahasi-e8a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWz3taCQbnNCBr9RVorxV6RT5LaRpZgn0',
    appId: '1:1073648909920:ios:a70a8008e5e505924c8d05',
    messagingSenderId: '1073648909920',
    projectId: 'aplikasi-olahraga-mahasi-e8a84',
    storageBucket: 'aplikasi-olahraga-mahasi-e8a84.appspot.com',
    iosBundleId: 'com.example.projekAplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWz3taCQbnNCBr9RVorxV6RT5LaRpZgn0',
    appId: '1:1073648909920:ios:a70a8008e5e505924c8d05',
    messagingSenderId: '1073648909920',
    projectId: 'aplikasi-olahraga-mahasi-e8a84',
    storageBucket: 'aplikasi-olahraga-mahasi-e8a84.appspot.com',
    iosBundleId: 'com.example.projekAplikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhJncEg7riTVLzdainBwXBEyUcJdhDvU',
    appId: '1:1073648909920:web:00267b652e0147de4c8d05',
    messagingSenderId: '1073648909920',
    projectId: 'aplikasi-olahraga-mahasi-e8a84',
    authDomain: 'aplikasi-olahraga-mahasi-e8a84.firebaseapp.com',
    storageBucket: 'aplikasi-olahraga-mahasi-e8a84.appspot.com',
    measurementId: 'G-9CT0NFXP25',
  );
}
